[package]
name = "web_splats"
version = "0.1.0"
edition = "2021"
authors = ["Simon Niedermayr", "Josef Stumpfegger"]
description = "3D Gaussian Splatting Viewer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { version = "0.20.1" }
winit = "0.29.14"
cgmath = { version = "0.18.0", features = [
    "bytemuck",
], git = 'https://github.com/rustgd/cgmath' }
env_logger = "0.11"
clap = { version = "4.5.2", features = ["derive"] }
bytemuck = { version = "1.14.3", features = ["derive"] }
anyhow = "1.0.81"
ply-rs = "0.1.3"
byteorder = "1.5.0"
serde_json = "1.0.114"
serde = { version = "1.0.188", features = ["derive"] }
num-traits = "0.2.18"
half = { version = "2.4.0", features = ["bytemuck", "num-traits"] }
log = "0.4.21"
rayon = "1.9.0"
image = "0.25.0"
indicatif = "0.17.8"


egui = "0.28.1"
egui-wgpu = "0.28.1"
egui-winit = { version = "0.28.1", features = [], default-features = false }
egui_plot = "0.28.1"
egui_dnd = "0.9.1"

rand = "0.8.5"
npyz = { version = "0.8.3", features = ["npz", "half"], optional = true }
futures-intrusive = "0.5.0"
splines = { version = "4.3.1", features = [
    "cgmath",
], git = "https://github.com/KeKsBoTer/splines" }

[dev-dependencies]
wasm-bindgen-cli = "0.2.100"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "viewer"

[[bin]]
name = "video"
required-features = ["video"]

[features]
npz = ["dep:npyz"]
video = []

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = { version = "0.3.0", features = ["macro"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]

getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.92"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.42"
console_log = "1"
log = "0.4"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
web-sys = { version = "0.3.69" }

[profile.web-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
